### PR TITLE
Line comments instead of block comments 4

### PR DESCRIPTION
**Pull request by GinoGiotto**
Continuation of https://github.com/metamath/metamath-exe/pull/138.

This PR covers all (editable) h files. Same categories described in https://github.com/metamath/metamath-exe/pull/139 are applied. Comments that start with `/*!` are ignored.

### CODE REVIEW

**Comment by GinoGiotto** [comment]
@digama0 are these changes welcome? I could continue but I'm unsure if people want this since I'm not receiving any feedback.

**Comment by david-a-wheeler** [comment]
I'm pkay with changing to line comments.

That said, obviously these don't provide any functional improvements, so it's hard to get excited over the change:-).

**Review by tirix — APPROVED** [review]
Line comments should make it the source code a bit easier to read an maintain.
I think it was discussed and agreed in the past.

**Comment by digama0** [comment]
@GinoGiotto You have the green light to keep going with these PRs, sorry for the delay. Feel free to ping me if it looks like I've forgotten about it.

**Pull request merged**
