### PR TITLE
add a documentation draft

### PR DESCRIPTION
**Pull request by wlammen**
Since we need to improve our documentation I provide a suggestion here.  Please explore and comment your findings here.

### CODE REVIEW

**Comment by digama0** [comment]
How about using markdown instead of AsciiDoc? They seem to have similar feature sets, but markdown is more well known and in particular gets rendered in github automatically without requiring users to copy the text into https://asciidoclive.com .

**Comment by wlammen** [comment]
@digama0 OK.  A quick lookup on Wikipedia indicates there is possibly no easy transformation into PDF or HTML.  Can that he solved?

**Comment by digama0** [comment]
Markdown to HTML is available in many places, if you want something equivalent to asciidoclive I suggest https://stackedit.io . Searching for markdown to PDF also yields a bunch of results, online services and so on.

**Comment by wlammen** [comment]
In our company we use proprietary software for documentation, so I looked out for something different.  I am not particularly committed to AsciiDoc, anything similar, or even better suits me well.  But should arrive at a decision quickly, so documentation can start.

**Comment by digama0** [comment]
That is, I advocate a documentation style like [this](https://github.com/leanprover-community/lean/tree/master/doc): just loose md files lying about (or collected in a `doc` folder), reachable via links in the readme to make it a kind of low effort static website.

**Comment by jkingdon** [comment]
> That is, I advocate a documentation style like [this](https://github.com/leanprover-community/lean/tree/master/doc): just loose md files lying about (or collected in a `doc` folder), reachable via links in the readme to make it a kind of low effort static website.

If people want to make the case for something else, I'm open to hearing it, but this "directory full of .md files" does strike me as probably the easiest way to "low effort static website".

**Pull request closed without merging**
